import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

import localFont from 'next/font/local'

const switzer = localFont({ src: [
  {
  path:'./fonts/Switzer-Regular.otf' ,
  weight:'400',
  style:'normal',
  },
  {
    path:'./fonts/Switzer-Light.otf' ,
    weight:'300',
    style:'normal',
  },
  {
    path:'./fonts/Switzer-Extralight.otf' ,
    weight:'200',
    style:'normal',
  },
  {
    path:'./fonts/Switzer-Medium.otf' ,
    weight:'500',
    style:'normal',
  },
  {
    path:'./fonts/Switzer-Black.otf' ,
    weight:'900',
    style:'normal',
  }
],
variable:'--font-switzer',
display:"swap",

})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={switzer.variable}>{children}</body>
    </html>
  )
}
